export enum UserAddressActionTypes {
    SET = "SET",
    CLEAR = "CLEAR"
}

export enum TezosActionTypes {
    SET_WALLET = "SET_WALLET",
    SET_PUBLIC_TOKEN = "SET_PUBLIC_TOKEN",
    CLEAR_PUBLIC_TOKEN = "CLEAR_PUBLIC_TOKEN",
    SET_BEACON_CONNECTION = "SET_BEACON_CONNECTION"
}

export enum SwapTokenTypes {
    SET_FIRST_ADDRESS = "SET_FIRST_ADDRESS",
    SET_SECOND_ADDRESS = "SET_SECOND_ADDRESS"
}